spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource         #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      #
  type-aliases-package: com.joker.springcloud.entities    #所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                     #mapper映射文件
      
eureka:
  client:  #客户端注册进Eureka服务列表内
    service-url:
      #单机版defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/   #集群版
  instance:
    instance-id: microservicecloud-dept8001  #自定义服务名称信息-eureka
    prefer-ip-address: true    #访问路径可以显示IP地址
    
info: 
  app.name: joker-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource         #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      #
  type-aliases-package: com.joker.springcloud.entities    #所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                     #mapper映射文件
      
eureka:
  client:  #客户端注册进Eureka服务列表内
    service-url:
      #单机版defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/   #集群版
  instance:
    instance-id: microservicecloud-dept8001  #自定义服务名称信息-eureka
    prefer-ip-address: true    #访问路径可以显示IP地址
    
info: 
  app.name: joker-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

